###############################################################
# MODULE: KeyVaultSecrets - Variables
###############################################################

variable "key_vault_id" {
  type        = string
  description = "Key Vault resource ID to push secrets to."
  nullable    = false

  validation {
    condition     = can(regex("^/subscriptions/[^/]+/resourceGroups/[^/]+/providers/Microsoft\\.KeyVault/vaults/[^/]+$", var.key_vault_id))
    error_message = "key_vault_id must be a valid Azure Key Vault resource ID."
  }
}

variable "tags" {
  type        = map(string)
  default     = {}
  nullable    = false
  description = "Module-level tags merged with per-secret tags + CreatedOn. Per-secret tags win on conflict."
}

variable "secrets" {
  description = <<-EOT
  Map of secrets to create in the Key Vault.
  Either `value` OR `generate` must be set (mutually exclusive).

  - `name`            - (Required) Secret name.
  - `value`           - (Optional) Explicit secret value.
  - `generate`        - (Optional) If set, random password generated by the module:
    - `length`         - (Optional) Password length. Defaults to 32.
    - `special`        - (Optional) Include special chars. Defaults to true.
    - `override_special` - (Optional) Restrict special chars to this set.
  - `content_type`    - (Optional) Metadata describing the secret (e.g. "password", "key").
  - `expiration_date` - (Optional) Explicit ISO 8601 expiration (e.g. "2027-01-01T00:00:00Z").
                        Mutually exclusive with expiration_days.
  - `expiration_days` - (Optional) Days from creation; rendered via time_offset for stability.
                        Required by ALZ policy "Secrets should have max validity period".
  - `tags`            - (Optional) Tags on the secret.
  EOT
  type = map(object({
    name  = string
    value = optional(string)
    generate = optional(object({
      length           = optional(number, 32)
      special          = optional(bool, true)
      override_special = optional(string)
    }))
    content_type    = optional(string)
    expiration_date = optional(string)
    not_before_date = optional(string)
    expiration_days = optional(number)
    tags            = optional(map(string), {})
  }))
  nullable  = false
  sensitive = true

  validation {
    condition = alltrue([
      for k, v in var.secrets :
      (v.value != null) != (v.generate != null) # exactly one must be set
    ])
    error_message = "Each secret must have exactly one of `value` or `generate` set."
  }

  validation {
    condition = alltrue([
      for k, v in var.secrets :
      !(v.expiration_date != null && v.expiration_days != null)
    ])
    error_message = "Each secret must have at most one of `expiration_date` or `expiration_days`, not both."
  }

  validation {
    condition = alltrue([
      for k, v in var.secrets :
      can(regex("^[a-zA-Z][a-zA-Z0-9-]{0,126}$", v.name))
    ])
    error_message = "Each secret name must start with a letter, contain only alphanumerics and hyphens, and be at most 127 characters (Azure Key Vault constraints)."
  }

  validation {
    condition = alltrue([
      for k, v in var.secrets :
      v.expiration_date == null || can(regex("^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}Z$", v.expiration_date))
    ])
    error_message = "expiration_date must be a UTC RFC3339 datetime string (e.g. \"2027-12-31T23:59:00Z\")."
  }

  validation {
    condition = alltrue([
      for k, v in var.secrets :
      v.not_before_date == null || can(regex("^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}Z$", v.not_before_date))
    ])
    error_message = "not_before_date must be a UTC RFC3339 datetime string (e.g. \"2027-01-01T00:00:00Z\")."
  }
}
