###############################################################
# MODULE: DiskEncryptionSet - Variables
#
# Each validation lives on the variable it is really about — Terraform
# requires a validation condition to reference its own variable, so an
# "anchor variable" carrying every cross-variable rule does not compile.
# Cross-variable references need Terraform 1.9+; version.tf pins 1.12.
#
# Deliberately `validation` and not `check`: a check only warns, and
# every rule here describes a configuration that either fails at apply
# or breaks SILENTLY at runtime. Both deserve a hard stop at plan time.
###############################################################

variable "name" {
  type        = string
  description = "Explicit Disk Encryption Set name. When null (default), the name is generated by ../Naming as des-{subscription_acronym}-{environment}-{region_code}-{workload}."
  default     = null

  # A generated name needs every segment ../Naming consumes. Catching it
  # here beats a confusing error from inside the naming module.
  validation {
    condition = var.name != null || alltrue([
      var.subscription_acronym != null,
      var.environment != null,
      var.region_code != null,
      var.workload != null,
    ])
    error_message = "Set var.name, or all of subscription_acronym / environment / region_code / workload so ../Naming can generate one."
  }
}

variable "subscription_acronym" {
  type        = string
  description = "Subscription acronym used by ../Naming (e.g. 'avd'). Ignored when var.name is set."
  default     = null
}

variable "environment" {
  type        = string
  description = "Environment segment used by ../Naming (e.g. 'prod'). Ignored when var.name is set."
  default     = null
}

variable "region_code" {
  type        = string
  description = "Short region code used by ../Naming (e.g. 'gwc'). Ignored when var.name is set."
  default     = null
}

variable "workload" {
  type        = string
  description = "Workload segment used by ../Naming (e.g. '01'). Ignored when var.name is set."
  default     = null
}

variable "resource_group_name" {
  type        = string
  description = "Resource group holding the Disk Encryption Set."
  nullable    = false
}

variable "location" {
  type        = string
  description = "Azure region. MUST match the region of the disks it encrypts — a DES is regional, and a disk cannot reference one from another region."
  nullable    = false
}

variable "key_vault_key_id" {
  type        = string
  description = <<-EOT
    Key Vault key backing the encryption. RSA 2048+ (or RSA-HSM on a Premium
    vault). The vault MUST have purge protection enabled — Azure refuses the
    DES otherwise, and enabling it is irreversible.

    Versionless (`.../keys/<name>`) when auto_key_rotation_enabled = true,
    versioned (`.../keys/<name>/<version>`) when false. The pairing is
    validated on auto_key_rotation_enabled.
  EOT
  nullable    = false
}

variable "key_vault_id" {
  type        = string
  description = "Key Vault holding the key, used to grant the DES identity 'Key Vault Crypto Service Encryption User'. Set to null ONLY if that grant is made out-of-band — without it, disks fail to attach to this DES."
  default     = null
}

variable "auto_key_rotation_enabled" {
  type        = bool
  description = "Follow the key's rotation policy automatically. Requires a VERSIONLESS key_vault_key_id. Default true — a CMK you never rotate buys the compliance checkbox and none of the security."
  default     = true

  # The pairing that fails SILENTLY: rotation on + a versioned key id
  # pins the DES to that version forever and the rotation policy is
  # never followed. Nothing errors, the key just never rotates.
  validation {
    condition     = var.auto_key_rotation_enabled != (length(regexall("/keys/[^/]+/[^/]+$", var.key_vault_key_id)) > 0)
    error_message = "auto_key_rotation_enabled = true requires a VERSIONLESS key_vault_key_id (.../keys/<name>); with a versioned id (.../keys/<name>/<version>) it must be false, otherwise the DES pins to that version and silently stops following the rotation policy."
  }
}

variable "encryption_type" {
  type        = string
  description = <<-EOT
    - `EncryptionAtRestWithCustomerKey` (default): CMK on the disk data.
      What the ALZ guardrail deny-osanddatadisk-cmk requires.
    - `EncryptionAtRestWithPlatformAndCustomerKeys`: double encryption.
    - `ConfidentialVmEncryptedWithCustomerKey`: **Confidential VMs only**,
      NOT Trusted Launch. Selecting it for a Trusted Launch host makes the
      VM unbootable. Accepted here because the module cannot know what will
      consume the DES — the caller owns that check.
  EOT
  default     = "EncryptionAtRestWithCustomerKey"

  validation {
    condition = contains([
      "EncryptionAtRestWithCustomerKey",
      "EncryptionAtRestWithPlatformAndCustomerKeys",
      "ConfidentialVmEncryptedWithCustomerKey",
    ], var.encryption_type)
    error_message = "encryption_type must be EncryptionAtRestWithCustomerKey, EncryptionAtRestWithPlatformAndCustomerKeys or ConfidentialVmEncryptedWithCustomerKey."
  }
}

variable "identity_type" {
  type        = string
  description = "Managed identity type: 'SystemAssigned' (default) or 'UserAssigned'. SystemAssigned ties the identity's lifecycle to the DES, which is what you want unless a pre-existing identity already holds the vault grant."
  default     = "SystemAssigned"

  validation {
    condition     = contains(["SystemAssigned", "UserAssigned"], var.identity_type)
    error_message = "identity_type must be SystemAssigned or UserAssigned."
  }
}

variable "user_assigned_identity_ids" {
  type        = list(string)
  description = "User-assigned identity IDs. Required when identity_type = 'UserAssigned', must be empty otherwise."
  default     = []

  # UserAssigned with no ids yields a DES with no usable identity; ids
  # passed alongside SystemAssigned are silently ignored by Azure.
  validation {
    condition     = (var.identity_type == "UserAssigned") == (length(var.user_assigned_identity_ids) > 0)
    error_message = "identity_type = 'UserAssigned' requires a non-empty user_assigned_identity_ids, and 'SystemAssigned' requires it empty."
  }
}

variable "federated_client_id" {
  type        = string
  description = "Multi-tenant application client ID for cross-tenant CMK. Leave null for the single-tenant case."
  default     = null
}

variable "tags" {
  type        = map(string)
  description = "Tags applied to the Disk Encryption Set."
  default     = {}
}
